[package]
name = "nostr-dm"
version = "0.1.0"
edition = "2024"

[dependencies]
nostr-sdk = "0.40"
thiserror = "2.0.12"
tokio = "1.44.2"
serde_json = "1.0"

tracing = "0.1"
tracing-subscriber = "0.3"

